# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shenghao Yang
author: Shenghao Yang
email: shenghao.yang@gmail.com
contacts:
  research:
    email: shyang@cuhk.edu.cn
    address: >
      Room 606, Cheng Dao Building<br/>
      2001 Longxiang Blvd.<br/>
      Longgang District, Shenzhen, China 818172
description: > # this means to ignore newlines until "baseurl:"
  Research Assistant Professor at CUHK(SZ)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shhyang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  shhyang

# Build settings
markdown: kramdown
gems: [jekyll/scholar]
exclude:
  - Gemfile
  - Gemfile.lock
