# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: shenghao yang
author: Shenghao Yang
email: shenghao.yang@gmail.com
contacts:
  academic:
    position: Research Assistant Professor
    affiliation: The Chinese University of Hong Kong, Shenzhen
    email: shyang@cuhk.edu.cn
    web: "http://www.cuhk.edu.cn"
    address: >
      Room 606, Cheng Dao Building<br/>
      The Chinese University of Hong Kong, Shenzhen<br/>
      2001 Longxiang Blvd.<br/>
      Longgang District, Shenzhen, China 818172
  research:
    position: researcher
    affiliation: Shenzhen Research Institute of Big Data
    email:
    web: "http://www.sribd.cn"
    address:
description: > # this means to ignore newlines until "baseurl:"
  A homepage generate by jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shhyang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  shhyang

# collections
collections:
  research:
    output: true
    permalink: /research/:path/
# bibliography
scholar:
  style: apa
  locale: en
  sort_by: year
  order: descending
  group_by: none
  group_order: ascending
  source: ./_data
  bibliography: yang.bib
  bibliography_template: ""
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: false
  query: "@*"
# theme: minima
# Build settings
markdown: kramdown
gems: ['jekyll/scholar']
exclude:
  - Gemfile
  - Gemfile.lock
  - update_github.sh
